export enum PermissionCode {
    // Project
    PROJECT_CREATE = "PROJECT_CREATE",
    PROJECT_READ = "PROJECT_READ",
    PROJECT_UPDATE = "PROJECT_UPDATE",
    PROJECT_DELETE = "PROJECT_DELETE",
    PROJECT_CHANGE_STATE = "PROJECT_CHANGE_STATE",
    PROJECT_VIEW_PROGRESS = "PROJECT_VIEW_PROGRESS",

    // Task
    TASK_CREATE = "TASK_CREATE",
    TASK_READ = "TASK_READ",
    TASK_UPDATE = "TASK_UPDATE",
    TASK_DELETE = "TASK_DELETE",
    TASK_ASSIGN = "TASK_ASSIGN",
    TASK_CHANGE_STATE = "TASK_CHANGE_STATE",
    TASK_CHANGE_PRIORITY = "TASK_CHANGE_PRIORITY",
    TASK_CHANGE_DUE_DATE = "TASK_CHANGE_DUE_DATE",

    // User
    USER_CREATE = "USER_CREATE",
    USER_READ = "USER_READ",
    USER_UPDATE = "USER_UPDATE",
    USER_DELETE = "USER_DELETE",
    USER_CHANGE_ROLE = "USER_CHANGE_ROLE",

    // Team
    TEAM_CREATE = "TEAM_CREATE",
    TEAM_READ = "TEAM_READ",
    TEAM_UPDATE = "TEAM_UPDATE",
    TEAM_DELETE = "TEAM_DELETE",
    TEAM_ADD_MEMBER = "TEAM_ADD_MEMBER",
    TEAM_REMOVE_MEMBER = "TEAM_REMOVE_MEMBER",

    // Comment
    COMMENT_CREATE = "COMMENT_CREATE",
    COMMENT_READ = "COMMENT_READ",
    COMMENT_UPDATE = "COMMENT_UPDATE",
    COMMENT_DELETE = "COMMENT_DELETE",

    // Document
    DOCUMENT_CREATE = "DOCUMENT_CREATE",
    DOCUMENT_READ = "DOCUMENT_READ",
    DOCUMENT_DELETE = "DOCUMENT_DELETE",

    // Activity
    ACTIVITY_READ = "ACTIVITY_READ",

    // Authorization
    ROLE_READ = "ROLE_READ",
    PERMISSION_READ = "PERMISSION_READ",
}

export interface Permission {
    id: number,
    code: PermissionCode,
    description: string | null
}

